// Enhanced Mock Data cho VSM CMS System với đầy đủ roles và permissions

export const mockUsers = [
  {
    id: 1,
    name: "Nguyễn Văn Admin",
    email: "admin@vsm.vn",
    role: "admin",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "IT",
    lastLogin: "2025-01-07T10:30:00Z",
    status: "active",
    permissions: ["all"],
    phone: "+84 123 456 789",
    position: "System Administrator",
  },
  {
    id: 2,
    name: "Trần Thị Leader",
    email: "leader@vsm.vn",
    role: "leader",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Development",
    lastLogin: "2025-01-07T09:15:00Z",
    status: "active",
    permissions: ["manage_team", "create_events", "view_analytics"],
    phone: "+84 987 654 321",
    position: "Team Leader",
  },
  {
    id: 3,
    name: "Lê Văn Developer",
    email: "dev@vsm.vn",
    role: "developer",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Development",
    lastLogin: "2025-01-06T16:45:00Z",
    status: "active",
    permissions: ["edit_websites", "view_analytics"],
    phone: "+84 555 123 456",
    position: "Senior Developer",
  },
  {
    id: 4,
    name: "Phạm Thị Designer",
    email: "designer@vsm.vn",
    role: "designer",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Design",
    lastLogin: "2025-01-07T08:20:00Z",
    status: "active",
    permissions: ["edit_design", "manage_media"],
    phone: "+84 777 888 999",
    position: "UI/UX Designer",
  },
  {
    id: 5,
    name: "Hoàng Văn Editor",
    email: "editor@vsm.vn",
    role: "editor",
    avatar: "/placeholder.svg?height=40&width=40",
    department: "Content",
    lastLogin: "2025-01-07T07:30:00Z",
    status: "active",
    permissions: ["edit_content", "manage_media"],
    phone: "+84 333 222 111",
    position: "Content Editor",
  },
]

// Current user context - Now dynamic for testing
let _currentUser = mockUsers[0] // Default to admin

export const getCurrentUser = () => _currentUser

export const setCurrentUser = (userId: number) => {
  const user = mockUsers.find((u) => u.id === userId)
  if (user) {
    _currentUser = user
  }
}

// For backward compatibility
export const currentUser = getCurrentUser()

export const mockCalendarEvents = [
  {
    id: 1,
    title: "Họp team phát triển",
    description: "Review tiến độ dự án website mới và phân công công việc tuần tới",
    startTime: "2025-01-07T09:00:00Z",
    endTime: "2025-01-07T10:30:00Z",
    type: "meeting",
    priority: "high",
    attendees: [mockUsers[0], mockUsers[1], mockUsers[2]],
    location: "Phòng họp A - Tầng 2",
    status: "confirmed",
    createdBy: mockUsers[1],
    isRecurring: true,
    recurringPattern: "weekly",
    reminders: [15, 60], // minutes before
    color: "#3b82f6",
  },
  {
    id: 2,
    title: "Deadline thiết kế UI",
    description: "Hoàn thành thiết kế giao diện trang chủ cho dự án ABC Company",
    startTime: "2025-01-07T17:00:00Z",
    endTime: "2025-01-07T17:00:00Z",
    type: "deadline",
    priority: "urgent",
    attendees: [mockUsers[3]],
    status: "pending",
    createdBy: mockUsers[1],
    isRecurring: false,
    reminders: [30, 120],
    color: "#dc2626",
  },
  {
    id: 3,
    title: "Demo sản phẩm cho khách hàng",
    description: "Trình bày tính năng mới của hệ thống CMS cho khách hàng XYZ",
    startTime: "2025-01-08T14:00:00Z",
    endTime: "2025-01-08T15:00:00Z",
    type: "presentation",
    priority: "high",
    attendees: [mockUsers[0], mockUsers[1], mockUsers[2]],
    location: "Online - Zoom Meeting",
    status: "confirmed",
    createdBy: mockUsers[0],
    isRecurring: false,
    reminders: [15, 60],
    color: "#059669",
  },
  {
    id: 4,
    title: "Training: VSM CMS Advanced",
    description: "Đào tạo tính năng nâng cao của VSM CMS cho toàn bộ team",
    startTime: "2025-01-09T13:00:00Z",
    endTime: "2025-01-09T16:00:00Z",
    type: "training",
    priority: "medium",
    attendees: mockUsers,
    location: "Phòng đào tạo - Tầng 3",
    status: "confirmed",
    createdBy: mockUsers[0],
    isRecurring: false,
    reminders: [30, 1440], // 30 min and 1 day before
    color: "#7c3aed",
  },
  {
    id: 5,
    title: "Code Review Session",
    description: "Review code cho module authentication mới",
    startTime: "2025-01-08T10:00:00Z",
    endTime: "2025-01-08T11:00:00Z",
    type: "meeting",
    priority: "medium",
    attendees: [mockUsers[1], mockUsers[2]],
    location: "Dev Room",
    status: "confirmed",
    createdBy: mockUsers[2],
    isRecurring: false,
    reminders: [15],
    color: "#10b981",
  },
  {
    id: 6,
    title: "Design System Update",
    description: "Cập nhật design system và component library",
    startTime: "2025-01-09T09:00:00Z",
    endTime: "2025-01-09T10:30:00Z",
    type: "meeting",
    priority: "medium",
    attendees: [mockUsers[3], mockUsers[1]],
    location: "Design Studio",
    status: "confirmed",
    createdBy: mockUsers[3],
    isRecurring: false,
    reminders: [15],
    color: "#8b5cf6",
  },
  {
    id: 7,
    title: "Content Planning Meeting",
    description: "Lên kế hoạch nội dung cho Q1 2025",
    startTime: "2025-01-10T14:00:00Z",
    endTime: "2025-01-10T15:30:00Z",
    type: "meeting",
    priority: "medium",
    attendees: [mockUsers[4], mockUsers[1]],
    location: "Content Room",
    status: "confirmed",
    createdBy: mockUsers[4],
    isRecurring: false,
    reminders: [30],
    color: "#f59e0b",
  },
]

export const mockChatRooms = [
  {
    id: 1,
    name: "🚀 Team Development",
    type: "group",
    avatar: "TD",
    description: "Nhóm thảo luận phát triển sản phẩm",
    members: [mockUsers[0], mockUsers[1], mockUsers[2]],
    lastMessage: {
      id: 101,
      userId: 2,
      message: "Đã hoàn thành tính năng authentication mới 🎉",
      timestamp: "2025-01-07T10:45:00Z",
      type: "text",
    },
    unreadCount: 3,
    isOnline: true,
    isPinned: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "🎨 Design Team",
    type: "group",
    avatar: "DT",
    description: "Nhóm thiết kế UI/UX",
    members: [mockUsers[0], mockUsers[3]],
    lastMessage: {
      id: 102,
      userId: 4,
      message: "Mockup mới đã sẵn sàng để review",
      timestamp: "2025-01-07T09:30:00Z",
      type: "text",
    },
    unreadCount: 1,
    isOnline: false,
    isPinned: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 3,
    name: "📝 Content Team",
    type: "group",
    avatar: "CT",
    description: "Nhóm quản lý nội dung",
    members: [mockUsers[0], mockUsers[4]],
    lastMessage: {
      id: 103,
      userId: 5,
      message: "Đã cập nhật content cho trang About Us",
      timestamp: "2025-01-07T08:15:00Z",
      type: "text",
    },
    unreadCount: 0,
    isOnline: true,
    isPinned: false,
    createdAt: "2025-01-01T00:00:00Z",
  },
  {
    id: 4,
    name: "👥 All Team",
    type: "group",
    avatar: "AT",
    description: "Nhóm chat toàn bộ team",
    members: mockUsers,
    lastMessage: {
      id: 104,
      userId: 1,
      message: "Meeting tổng kết tuần vào 3PM hôm nay",
      timestamp: "2025-01-07T07:45:00Z",
      type: "text",
    },
    unreadCount: 2,
    isOnline: true,
    isPinned: true,
    createdAt: "2025-01-01T00:00:00Z",
  },
]

export const mockChatMessages = [
  {
    id: 1,
    roomId: 1,
    userId: 2,
    message: "Chào mọi người! Tính năng authentication đã hoàn thành ✅",
    timestamp: "2025-01-07T10:30:00Z",
    type: "text",
    reactions: [
      { emoji: "👍", users: [1, 3], count: 2 },
      { emoji: "🎉", users: [1], count: 1 },
    ],
    isEdited: false,
    replyTo: null,
  },
  {
    id: 2,
    roomId: 1,
    userId: 1,
    message: "Tuyệt vời! Có thể demo được không? 🚀",
    timestamp: "2025-01-07T10:32:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 1,
  },
  {
    id: 3,
    roomId: 1,
    userId: 3,
    message: "Mình đã test và hoạt động rất tốt! Performance cũng được cải thiện đáng kể 📈",
    timestamp: "2025-01-07T10:35:00Z",
    type: "text",
    reactions: [{ emoji: "💯", users: [1, 2], count: 2 }],
    isEdited: false,
    replyTo: null,
  },
  {
    id: 4,
    roomId: 1,
    userId: 1,
    message: "Perfect! Merge vào main branch và deploy lên staging nhé 🎯",
    timestamp: "2025-01-07T10:36:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: null,
  },
  {
    id: 5,
    roomId: 1,
    userId: 2,
    message: "Đã merge xong và deploy thành công! Link staging: https://staging.vsm.vn 🌟",
    timestamp: "2025-01-07T10:38:00Z",
    type: "text",
    reactions: [
      { emoji: "🚀", users: [1, 3], count: 2 },
      { emoji: "👏", users: [1], count: 1 },
    ],
    isEdited: false,
    replyTo: null,
  },
  // Design team messages
  {
    id: 6,
    roomId: 2,
    userId: 4,
    message: "Đã hoàn thành design cho trang dashboard mới 🎨",
    timestamp: "2025-01-07T09:30:00Z",
    type: "text",
    reactions: [{ emoji: "😍", users: [1], count: 1 }],
    isEdited: false,
    replyTo: null,
  },
  {
    id: 7,
    roomId: 2,
    userId: 1,
    message: "Design rất đẹp! Có thể share link Figma không?",
    timestamp: "2025-01-07T09:32:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 6,
  },
  // Content team messages
  {
    id: 8,
    roomId: 3,
    userId: 5,
    message: "Đã cập nhật toàn bộ content cho website ABC Company ✍️",
    timestamp: "2025-01-07T08:15:00Z",
    type: "text",
    reactions: [{ emoji: "👍", users: [1], count: 1 }],
    isEdited: false,
    replyTo: null,
  },
  // All team messages
  {
    id: 9,
    roomId: 4,
    userId: 1,
    message: "Chào mọi người! Meeting tổng kết tuần vào 3PM hôm nay tại phòng họp A 📅",
    timestamp: "2025-01-07T07:45:00Z",
    type: "text",
    reactions: [{ emoji: "👍", users: [2, 3, 4, 5], count: 4 }],
    isEdited: false,
    replyTo: null,
  },
  {
    id: 10,
    roomId: 4,
    userId: 2,
    message: "Noted! Sẽ chuẩn bị báo cáo tiến độ development",
    timestamp: "2025-01-07T07:47:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 9,
  },
  {
    id: 11,
    roomId: 4,
    userId: 3,
    message: "Mình sẽ demo tính năng mới đã hoàn thành",
    timestamp: "2025-01-07T07:48:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 9,
  },
  {
    id: 12,
    roomId: 4,
    userId: 4,
    message: "Design system update cũng đã sẵn sàng để present",
    timestamp: "2025-01-07T07:49:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 9,
  },
  {
    id: 13,
    roomId: 4,
    userId: 5,
    message: "Content strategy cho Q1 đã hoàn thành, sẽ share trong meeting",
    timestamp: "2025-01-07T07:50:00Z",
    type: "text",
    reactions: [],
    isEdited: false,
    replyTo: 9,
  },
]

export const mockAnalytics = {
  totalViews: 125430,
  totalWebsites: 18,
  totalUsers: 67,
  conversionRate: 4.2,
  monthlyGrowth: 18.5,
  weeklyGrowth: 5.2,
  topPages: [
    { page: "/", views: 25420, bounce: 32.1, avgTime: "2:45" },
    { page: "/about", views: 18930, bounce: 38.7, avgTime: "1:52" },
    { page: "/services", views: 16750, bounce: 35.2, avgTime: "3:12" },
    { page: "/contact", views: 12320, bounce: 25.9, avgTime: "1:38" },
    { page: "/blog", views: 9840, bounce: 42.3, avgTime: "4:23" },
  ],
  trafficSources: [
    { source: "Organic Search", percentage: 48.2, visitors: 35240, growth: 12.5 },
    { source: "Direct", percentage: 26.7, visitors: 19890, growth: 8.3 },
    { source: "Social Media", percentage: 15.8, visitors: 11560, growth: 25.7 },
    { source: "Referral", percentage: 9.3, visitors: 6180, growth: -2.1 },
  ],
  deviceStats: [
    { device: "Desktop", percentage: 52.3, visitors: 38240 },
    { device: "Mobile", percentage: 41.2, visitors: 30120 },
    { device: "Tablet", percentage: 6.5, visitors: 4760 },
  ],
  browserStats: [
    { browser: "Chrome", percentage: 68.4, visitors: 50020 },
    { browser: "Safari", percentage: 18.7, visitors: 13680 },
    { browser: "Firefox", percentage: 8.2, visitors: 5990 },
    { browser: "Edge", percentage: 4.7, visitors: 3440 },
  ],
}

export const mockMediaFiles = [
  {
    id: 1,
    name: "hero-banner-2024.jpg",
    type: "image",
    size: "2.4 MB",
    dimensions: "1920x1080",
    url: "/placeholder.svg?height=400&width=800",
    uploadedBy: mockUsers[3],
    uploadedAt: "2025-01-06T14:20:00Z",
    tags: ["banner", "hero", "homepage", "2024"],
    folder: "banners",
    isPublic: true,
    downloads: 45,
  },
  {
    id: 2,
    name: "company-logo-vector.svg",
    type: "image",
    size: "45 KB",
    dimensions: "500x200",
    url: "/placeholder.svg?height=100&width=200",
    uploadedBy: mockUsers[0],
    uploadedAt: "2025-01-05T09:15:00Z",
    tags: ["logo", "brand", "header", "vector"],
    folder: "logos",
    isPublic: true,
    downloads: 128,
  },
  {
    id: 3,
    name: "product-demo-video.mp4",
    type: "video",
    size: "15.8 MB",
    dimensions: "1280x720",
    url: "/placeholder-video.mp4",
    uploadedBy: mockUsers[2],
    uploadedAt: "2025-01-04T16:30:00Z",
    tags: ["demo", "product", "video", "tutorial"],
    folder: "videos",
    isPublic: false,
    downloads: 23,
  },
  {
    id: 4,
    name: "team-photo-2024.jpg",
    type: "image",
    size: "3.2 MB",
    dimensions: "2048x1365",
    url: "/placeholder.svg?height=400&width=600",
    uploadedBy: mockUsers[4],
    uploadedAt: "2025-01-03T11:45:00Z",
    tags: ["team", "photo", "about", "2024"],
    folder: "team",
    isPublic: true,
    downloads: 67,
  },
  {
    id: 5,
    name: "ui-components-sketch.sketch",
    type: "design",
    size: "8.7 MB",
    dimensions: "N/A",
    url: "/placeholder-file.sketch",
    uploadedBy: mockUsers[3],
    uploadedAt: "2025-01-02T10:30:00Z",
    tags: ["ui", "components", "design", "sketch"],
    folder: "design",
    isPublic: false,
    downloads: 12,
  },
  {
    id: 6,
    name: "blog-post-featured.jpg",
    type: "image",
    size: "1.8 MB",
    dimensions: "1200x800",
    url: "/placeholder.svg?height=300&width=450",
    uploadedBy: mockUsers[4],
    uploadedAt: "2025-01-01T15:20:00Z",
    tags: ["blog", "featured", "content"],
    folder: "blog",
    isPublic: true,
    downloads: 34,
  },
]

export const mockTemplates = [
  {
    id: 1,
    name: "Corporate Champion Pro",
    category: "business",
    description: "Template chuyên nghiệp cho doanh nghiệp hàng đầu với đầy đủ tính năng",
    thumbnail: "/placeholder.svg?height=200&width=300",
    price: 0,
    downloads: 2150,
    rating: 4.9,
    tags: ["business", "corporate", "professional", "responsive"],
    featured: true,
    premium: false,
    author: "VSM Team",
    lastUpdated: "2025-01-05T00:00:00Z",
    version: "2.1.0",
    compatibility: ["VSM CMS 2.0+"],
    demo: "https://demo.vsm.vn/corporate-champion",
  },
  {
    id: 2,
    name: "Creative Powerhouse Elite",
    category: "creative",
    description: "Template sáng tạo đỉnh cao cho agency và studio thiết kế",
    thumbnail: "/placeholder.svg?height=200&width=300",
    price: 199000,
    downloads: 1890,
    rating: 4.8,
    tags: ["creative", "agency", "portfolio", "animation"],
    featured: true,
    premium: true,
    author: "Design Masters",
    lastUpdated: "2025-01-03T00:00:00Z",
    version: "1.5.2",
    compatibility: ["VSM CMS 2.0+"],
    demo: "https://demo.vsm.vn/creative-powerhouse",
  },
  {
    id: 3,
    name: "E-commerce Pro Max",
    category: "ecommerce",
    description: "Template thương mại điện tử hoàn chỉnh với payment gateway",
    thumbnail: "/placeholder.svg?height=200&width=300",
    price: 299000,
    downloads: 1456,
    rating: 4.7,
    tags: ["ecommerce", "shop", "payment", "inventory"],
    featured: false,
    premium: true,
    author: "Commerce Team",
    lastUpdated: "2025-01-04T00:00:00Z",
    version: "3.0.1",
    compatibility: ["VSM CMS 2.0+"],
    demo: "https://demo.vsm.vn/ecommerce-pro",
  },
  {
    id: 4,
    name: "Blog Master Premium",
    category: "blog",
    description: "Template blog hiện đại với SEO tối ưu và social integration",
    thumbnail: "/placeholder.svg?height=200&width=300",
    price: 0,
    downloads: 3240,
    rating: 4.6,
    tags: ["blog", "seo", "social", "responsive"],
    featured: false,
    premium: false,
    author: "Content Team",
    lastUpdated: "2025-01-02T00:00:00Z",
    version: "1.8.3",
    compatibility: ["VSM CMS 1.5+"],
    demo: "https://demo.vsm.vn/blog-master",
  },
]

export const mockNotifications = [
  {
    id: 1,
    title: "🎉 Website mới được tạo",
    message: 'Website "Công ty ABC" đã được tạo thành công bởi Nguyễn Văn A',
    type: "success",
    time: "5 phút trước",
    read: false,
    userId: 1,
    actionUrl: "/dashboard/websites/1",
    priority: "normal",
  },
  {
    id: 2,
    title: "⚠️ Bảo trì hệ thống",
    message: "Hệ thống sẽ bảo trì vào 2:00 AM ngày mai (khoảng 30 phút)",
    type: "warning",
    time: "1 giờ trước",
    read: false,
    userId: null,
    actionUrl: null,
    priority: "high",
  },
  {
    id: 3,
    title: "👥 Thành viên mới",
    message: "Hoàng Văn Editor đã được thêm vào team Content",
    type: "info",
    time: "2 giờ trước",
    read: true,
    userId: 2,
    actionUrl: "/dashboard/users",
    priority: "normal",
  },
  {
    id: 4,
    title: "📊 Báo cáo tuần",
    message: "Báo cáo hiệu suất tuần này đã sẵn sàng để xem",
    type: "info",
    time: "1 ngày trước",
    read: false,
    userId: null,
    actionUrl: "/dashboard/analytics",
    priority: "low",
  },
  {
    id: 5,
    title: "🚀 Deploy thành công",
    message: "Website 'Landing Page X' đã được deploy lên production",
    type: "success",
    time: "3 giờ trước",
    read: true,
    userId: 3,
    actionUrl: "/dashboard/websites/2",
    priority: "normal",
  },
  {
    id: 6,
    title: "🎨 Design review cần approval",
    message: "Design mới cho homepage cần được review và approve",
    type: "info",
    time: "4 giờ trước",
    read: false,
    userId: 4,
    actionUrl: "/dashboard/designs/review",
    priority: "normal",
  },
  {
    id: 7,
    title: "📝 Content đã được xuất bản",
    message: "Bài viết 'VSM CMS Guide' đã được xuất bản thành công",
    type: "success",
    time: "6 giờ trước",
    read: true,
    userId: 5,
    actionUrl: "/dashboard/content/posts",
    priority: "normal",
  },
]

// Role permissions
export const rolePermissions = {
  admin: [
    "all", // Full access
  ],
  leader: [
    "manage_team",
    "create_events",
    "assign_tasks",
    "view_analytics",
    "manage_projects",
    "edit_websites",
    "manage_media",
    "create_websites",
    "delete_websites",
  ],
  developer: ["edit_websites", "view_analytics", "manage_media", "edit_code", "create_websites", "manage_technical"],
  designer: ["edit_design", "manage_media", "edit_websites", "create_websites", "manage_templates"],
  editor: ["edit_content", "manage_media", "create_websites", "manage_content"],
}

// Check if user has permission
export const hasPermission = (userRole: string, permission: string): boolean => {
  const permissions = rolePermissions[userRole as keyof typeof rolePermissions] || []
  return permissions.includes("all") || permissions.includes(permission)
}

// Role-specific website data
export const getRoleSpecificWebsites = (role: string) => {
  const baseWebsites = [
    {
      id: 1,
      name: "Website Công ty ABC",
      url: "abc-company.vsm.vn",
      domain: "abc-company.com",
      status: "published",
      template: "Corporate Champion",
      thumbnail: "/placeholder.svg?height=200&width=300",
      views: 12450,
      visitors: 8920,
      lastModified: "2025-01-07T10:30:00Z",
      createdAt: "2024-12-15T09:00:00Z",
      owner: { id: 1, name: "Nguyễn Văn Admin", role: "admin" },
      collaborators: [
        { id: 2, name: "Trần Thị Leader", role: "leader" },
        { id: 3, name: "Lê Văn Dev", role: "developer" },
      ],
      tags: ["business", "corporate"],
      performance: { speed: 95, seo: 88, accessibility: 92 },
      analytics: { viewsChange: 12, visitorsChange: 8, bounceRate: 35 },
    },
    {
      id: 2,
      name: "Landing Page Sản phẩm X",
      url: "product-x.vsm.vn",
      domain: "product-x.com",
      status: "draft",
      template: "Landing Victory",
      thumbnail: "/placeholder.svg?height=200&width=300",
      views: 3420,
      visitors: 2180,
      lastModified: "2025-01-06T15:20:00Z",
      createdAt: "2024-12-20T14:30:00Z",
      owner: { id: 3, name: "Lê Văn Dev", role: "developer" },
      collaborators: [{ id: 4, name: "Phạm Thị Designer", role: "designer" }],
      tags: ["landing", "product"],
      performance: { speed: 88, seo: 75, accessibility: 85 },
      analytics: { viewsChange: -5, visitorsChange: 15, bounceRate: 42 },
    },
    {
      id: 3,
      name: "Blog Cá nhân",
      url: "my-blog.vsm.vn",
      domain: "myblog.com",
      status: "published",
      template: "Blog Master",
      thumbnail: "/placeholder.svg?height=200&width=300",
      views: 8760,
      visitors: 5430,
      lastModified: "2025-01-05T11:45:00Z",
      createdAt: "2024-11-10T16:20:00Z",
      owner: { id: 5, name: "Hoàng Văn Editor", role: "editor" },
      collaborators: [],
      tags: ["blog", "personal"],
      performance: { speed: 92, seo: 95, accessibility: 88 },
      analytics: { viewsChange: 25, visitorsChange: 18, bounceRate: 28 },
    },
    {
      id: 4,
      name: "Portfolio Design",
      url: "portfolio.vsm.vn",
      domain: "myportfolio.com",
      status: "draft",
      template: "Portfolio Elite",
      thumbnail: "/placeholder.svg?height=200&width=300",
      views: 1250,
      visitors: 890,
      lastModified: "2025-01-04T09:15:00Z",
      createdAt: "2024-12-01T10:00:00Z",
      owner: { id: 4, name: "Phạm Thị Designer", role: "designer" },
      collaborators: [],
      tags: ["portfolio", "design"],
      performance: { speed: 90, seo: 70, accessibility: 82 },
      analytics: { viewsChange: 8, visitorsChange: 12, bounceRate: 38 },
    },
    {
      id: 5,
      name: "E-commerce Store",
      url: "store.vsm.vn",
      domain: "mystore.com",
      status: "published",
      template: "E-commerce Pro",
      thumbnail: "/placeholder.svg?height=200&width=300",
      views: 15680,
      visitors: 9240,
      lastModified: "2025-01-07T08:30:00Z",
      createdAt: "2024-10-15T12:00:00Z",
      owner: { id: 2, name: "Trần Thị Leader", role: "leader" },
      collaborators: [
        { id: 3, name: "Lê Văn Dev", role: "developer" },
        { id: 4, name: "Phạm Thị Designer", role: "designer" },
      ],
      tags: ["ecommerce", "store"],
      performance: { speed: 85, seo: 90, accessibility: 87 },
      analytics: { viewsChange: 22, visitorsChange: 16, bounceRate: 32 },
    },
  ]

  // Filter based on role
  switch (role) {
    case "admin":
      return baseWebsites // Admin sees all
    case "leader":
      return baseWebsites.filter(
        (w) =>
          w.owner.role === "leader" ||
          w.collaborators.some((c) => c.role === "leader") ||
          ["developer", "designer", "editor"].includes(w.owner.role),
      )
    case "developer":
      return baseWebsites.filter(
        (w) => w.owner.role === "developer" || w.collaborators.some((c) => c.role === "developer"),
      )
    case "designer":
      return baseWebsites.filter(
        (w) => w.owner.role === "designer" || w.collaborators.some((c) => c.role === "designer"),
      )
    case "editor":
      return baseWebsites.filter((w) => w.owner.role === "editor" || w.collaborators.some((c) => c.role === "editor"))
    default:
      return []
  }
}
